local ids = {
	wooden_chest = 1,
	iron_chest = 2,
	steel_chest = 3,
	storage_tank = 4,

	transport_belt = 5,
	fast_transport_belt = 6,
	express_transport_belt = 7,
	underground_belt = 8,
	fast_underground_belt = 9,
	express_underground_belt = 10,
	splitter = 11,
	fast_splitter = 12,
	express_splitter = 13,

	burner_inserter = 14,
	inserter = 15,
	long_inserter = 16,
	fast_inserter = 17,
	filter_inserter = 18,
	stack_inserter = 19,
	stack_filter_inserter = 20,

	small_electric_pole = 21,
	medium_electric_pole = 22,
	big_electric_pole = 23,
	substation = 24,

	pipe = 25,
	pipe_to_ground = 26,
	pump = 27,

	rail = 28,
	train_stop = 29,
	rail_signal = 30,
	rail_chain_signal = 31,

	logistic_chest_active_provider = 32,
	logistic_chest_passive_provider = 33,
	logistic_chest_storage = 34,
	logistic_chest_buffer = 35,
	logistic_chest_requester = 36,
	roboport = 37,

	lamp = 38,
	arithmetic_combinator = 39,
	decider_combinator = 40,
	constant_combinator = 41,
	power_switch = 42,
	programmable_speaker = 43,

	boiler = 44,
	steam_engine = 45,
	solar_panel = 46,
	accumulator = 47,
	nuclear_reactor = 48,
	heat_exchanger = 49,
	heat_pipe = 50,
	steam_turbine = 51,

	burner_mining_drill = 52,
	electric_mining_drill = 53,
	offshore_pump = 54,
	pumpjack = 55,

	stone_furnace = 56,
	steel_furnace = 57,
	electric_furnace = 58,

	assembling_machine_1 = 59,
	assembling_machine_2 = 60,
	assembling_machine_3 = 61,

	refinery = 62,
	chemical_plant = 63,
	centrifuge = 64,
	lab = 65,

	beacon = 66,

	rocket_silo = 67,

	wall = 68,
	gate = 69,

	gun_turret = 70,
	laser_turret = 71,
	flame_turret = 72,
	artillery_turret = 73,

	radar = 74,

	["1"] = "wooden_chest",
	["2"] = "iron_chest",
	["3"] = "steel_chest",
	["4"] = "storage_tank",
	["5"] = "transport_belt",
	["6"] = "fast_transport_belt",
	["7"] = "express_transport_belt",
	["8"] = "underground_belt",
	["9"] = "fast_underground_belt",
	["10"] = "express_underground_belt",
	["11"] = "splitter",
	["12"] = "fast_splitter",
	["13"] = "express_splitter",
	["14"] = "burner_inserter",
	["15"] = "inserter",
	["16"] = "long_inserter",
	["17"] = "fast_inserter",
	["18"] = "filter_inserter",
	["19"] = "stack_inserter",
	["20"] = "stack_filter_inserter",
	["21"] = "small_electric_pole",
	["22"] = "medium_electric_pole",
	["23"] = "big_electric_pole",
	["24"] = "substation",
	["25"] = "pipe",
	["26"] = "pipe_to_ground",
	["27"] = "pump",
	["28"] = "rail",
	["29"] = "train_stop",
	["30"] = "rail_signal",
	["31"] = "rail_chain_signal",
	["32"] = "logistic_chest_active_provider",
	["33"] = "logistic_chest_passive_provider",
	["34"] = "logistic_chest_storage",
	["35"] = "logistic_chest_buffer",
	["36"] = "logistic_chest_requester",
	["37"] = "roboport",
	["38"] = "lamp",
	["39"] = "arithmetic_combinator",
	["40"] = "decider_combinator",
	["41"] = "constant_combinator",
	["42"] = "power_switch",
	["43"] = "programmable_speaker",
	["44"] = "boiler",
	["45"] = "steam_engine",
	["46"] = "solar_panel",
	["47"] = "accumulator",
	["48"] = "nuclear_reactor",
	["49"] = "heat_exchanger",
	["50"] = "heat_pipe",
	["51"] = "steam_turbine",
	["52"] = "burner_mining_drill",
	["53"] = "electric_mining_drill",
	["54"] = "offshore_pump",
	["55"] = "pumpjack",
	["56"] = "stone_furnace",
	["57"] = "steel_furnace",
	["58"] = "electric_furnace",
	["59"] = "assembling_machine_1",
	["60"] = "assembling_machine_2",
	["61"] = "assembling_machine_3",
	["62"] = "refinery",
	["63"] = "chemical_plant",
	["64"] = "centrifuge",
	["65"] = "lab",
	["66"] = "beacon",
	["67"] = "rocket_silo",
	["68"] = "wall",
	["69"] = "gate",
	["70"] = "gun_turret",
	["71"] = "laser_turret",
	["72"] = "flame_turret",
	["73"] = "artillery_turret",
	["74"] = "radar",
}

return ids
